### PR TITLE
Post Y9999 dates, gmtime error checking, argc > 1 default codepath

### PR DESCRIPTION
**Pull request by iriswebb**
- Account for post-Y9999 dates
  * `./ud 99999999999999999999` segfaults because `gmtime()` returns NULL, check for `gmtime()` failures
  * Allocate space for large year numbers (the maximum that `gmtime` will allow is 10 bytes)
- Make `argv > 1` the default code path (Removes a layer of nesting)
- Replace `print_version()` with a `printf()` call
- Move `date_string_to_unix_day()` error handling into `date_string_to_unix_day()` (Which allows for the direct returning of the unix day).

### CODE REVIEW

**Comment by xyproto** [comment]
Great, thanks! Merged.

**Comment by xyproto** [comment]
The program still has some surprising behavior left.

Here is a quick test:

```
% python -c 'import os; [print("9" * x + ": " + str(os.system("./ud " + "9" * x))) for x in range(1, 30)]'
1970-01-10
9: 0
1970-04-10
99: 0
1972-09-26
999: 0
1997-05-18
9999: 0
2243-10-16
99999: 0
4707-11-28
999999: 0
29349-01-25
9999999: 0
275760-09-12
99999999: 0
2739877-01-02
999999999: 0
27381040-01-26
9999999999: 0
273792670-09-12
99999999999: 0
ud: Date conversion failed: Value too large for defined data type
999999999999: 256
ud: Date conversion failed: Value too large for defined data type
9999999999999: 256
ud: Date conversion failed: Value too large for defined data type
99999999999999: 256
ud: Date conversion failed: Value too large for defined data type
999999999999999: 256
ud: Date conversion failed: Value too large for defined data type
9999999999999999: 256
ud: Date conversion failed: Value too large for defined data type
99999999999999999: 256
ud: Date conversion failed: Value too large for defined data type
999999999999999999: 256
1969-12-31
9999999999999999999: 0
1969-12-31
99999999999999999999: 0
1969-12-31
999999999999999999999: 0
1969-12-31
9999999999999999999999: 0
1969-12-31
99999999999999999999999: 0
1969-12-31
999999999999999999999999: 0
1969-12-31
9999999999999999999999999: 0
1969-12-31
99999999999999999999999999: 0
1969-12-31
999999999999999999999999999: 0
1969-12-31
9999999999999999999999999999: 0
1969-12-31
99999999999999999999999999999: 0
```

Any idea how to tackle something like this? With custom number types?

**Comment by iriswebb** [comment]
After some quick debugging, this seems to be a result of a error from `strtoll`

This is solved by checking `errno` after `strtoll` is called

```c
    int64_t date_flag = strtoll(argv[1], &end, 10);
    if (errno == ERANGE)
        err(EXIT_FAILURE, "Date conversion failed");
```

**Comment by iriswebb** [comment]
Another way of checking this would to see if strtoll returns LLONG_MAX (gmtime can't parse that ,and this also wouldn't require to include errno.h)

```c
    int64_t date_flag = strtoll(argv[1], &end, 10);
    if (date_flag == LLONG_MAX)
        err(EXIT_FAILURE, "Date conversion failed");
```

**Comment by xyproto** [comment]
I added you as a collaborator, btw, in case you want to make improvements without going the route through PRs.

**Pull request merged**
